export const names={dots:'Dots',lines:'Lines',wavy:'Wavy lines',hash:'Hash grid',flakes:'Flakes'};
export const defaults={pattern:'dots',density:40,densityY:40,orientation:'horizontal',size:20,amplitude:15,frequency:4,seed:42,jitter:0,probability:100,dotMode:'random',dotMin:0,dotMax:100,dotWaves:3,dotDirection:'xy',rippleDirection:'forward',twinkleSharpness:3,gridStyle:'regular',gridLineWidth:1,gridLineDarkness:20,crossSize:24,crossWidth:2,crossDarkness:70,contrast:1,softness:0,threshold:128,invert:false,binary:false,layer:'none',blend:'multiply',motion:'scale',direction:'y',strength:50,cycles:1,duration:4,fps:24,resolution:1024,transparent:false};
export function random(seed){let a=seed|0;return()=>{a+=0x6d2b79f5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
const tau=Math.PI*2;
export function motionFor(pattern,motion){if(motion==='still')return 'still';return pattern==='dots'?'scale':pattern==='wavy'?'ripple':pattern==='flakes'?'twinkle':(['flow','pulse'].includes(motion)?motion:'flow');}
// Geometry and random attributes stay fixed. Only time-dependent properties change.
export function dotScale(s,phase,col,row,offset){const spatial=s.dotMode==='linear'?s.dotWaves*((s.dotDirection!=='y'?col/s.density:0)+(s.dotDirection!=='x'?row/s.densityY:0)):s.dotMode==='random'?offset:0;const value=.5+.5*Math.sin(tau*(phase*s.cycles-spatial));return (s.dotMin+(s.dotMax-s.dotMin)*value)/100;}
function base(canvas,s,phase,pattern=s.pattern){const c=canvas.getContext('2d'),w=canvas.width,n=s.density,m=s.densityY??n,p=((phase%1)+1)%1,motion=motionFor(pattern,s.motion),pulse=motion==='pulse'?1+s.strength/100*.7*Math.sin(p*tau*s.cycles):1,r=random(s.seed),cell=1/n;
 c.setTransform(w,0,0,w,0,0);if(s.orientation==='vertical')c.transform(0,1,1,0,0,0);c.fillStyle='white';c.fillRect(0,0,1,1);c.strokeStyle='black';c.fillStyle='black';c.lineWidth=s.size/1024*pulse;c.lineJoin='round';
 let dx=0,dy=0;if(motion==='flow'){dx=s.direction!=='y'?p*s.cycles:0;dy=s.direction!=='x'?p*s.cycles:0;}dx=dx%1;dy=dy%1;
 function wrap(draw){for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){c.save();c.translate(x+dx,y+dy);draw();c.restore();}}
 if(pattern==='dots'||pattern==='flakes'){const count=pattern==='dots'?n*m:n*n*3;for(let i=0;i<count;i++){const col=i%n,row=Math.floor(i/n);let x=pattern==='dots'?(col+.5)*cell:r(),y=pattern==='dots'?(row+.5)/m:r(),coverage=r(),offset=r(),j=s.jitter/100*cell;x+=(r()-.5)*j;y+=(r()-.5)*j;let radius=s.size/1024/2*(pattern==='flakes'?(.2+r()*1.8):1);if(pattern==='dots'&&motion==='scale')radius*=dotScale(s,p,col,row,offset);const brightness=motion==='twinkle'?Math.pow(.5+.5*Math.sin(tau*(p*s.cycles+offset)),s.twinkleSharpness):1;const tone=Math.round(255*(1-brightness));c.fillStyle=`rgb(${tone} ${tone} ${tone})`;if(coverage*100>s.probability)continue;wrap(()=>{c.beginPath();if(pattern==='dots')c.arc(x,y,Math.max(0,radius),0,tau);else{c.moveTo(x-radius,y);c.lineTo(x+radius*.4,y-radius);c.lineTo(x+radius,y+radius*.5);c.lineTo(x-radius*.3,y+radius);c.closePath();}c.fill();});}}
 else if(pattern==='lines'||pattern==='wavy'||pattern==='hash'){wrap(()=>{const marked=pattern==='hash'&&s.gridStyle==='crosses';if(marked){const tone=Math.round(255*(1-s.gridLineDarkness/100));c.strokeStyle=`rgb(${tone} ${tone} ${tone})`;c.lineWidth=s.gridLineWidth/1024*pulse;}for(let i=0;i<(pattern==='hash'?m:n);i++){const y=(i+.5)/(pattern==='hash'?m:n);c.beginPath();if(pattern==='wavy'){for(let k=-8;k<=520;k++){let x=k/512,amp=s.amplitude/1024,shift=motion==='ripple'?p*tau*s.cycles*(s.rippleDirection==='reverse'?1:-1):0;let yy=y+Math.sin(x*tau*s.frequency+shift)*amp;k===-8?c.moveTo(x,yy):c.lineTo(x,yy);}}else{c.moveTo(-.01,y);c.lineTo(1.01,y);}c.stroke();}if(pattern==='hash'){for(let i=0;i<n;i++){const x=(i+.5)/n;c.beginPath();c.moveTo(x,-.01);c.lineTo(x,1.01);c.stroke();}}if(marked){const tone=Math.round(255*(1-s.crossDarkness/100)),arm=s.crossSize/2048*pulse;c.strokeStyle=`rgb(${tone} ${tone} ${tone})`;c.lineWidth=s.crossWidth/1024*pulse;c.beginPath();for(let row=0;row<m;row++)for(let col=0;col<n;col++){const x=(col+.5)/n,y=(row+.5)/m;c.moveTo(x-arm,y);c.lineTo(x+arm,y);c.moveTo(x,y-arm);c.lineTo(x,y+arm);}c.stroke();}});}
 c.setTransform(1,0,0,1,0,0);
}
export function render(canvas,s,phase){base(canvas,s,phase);let c=canvas.getContext('2d',{willReadFrequently:true}),w=canvas.width;if(s.layer!=='none'){const other=document.createElement('canvas');other.width=other.height=w;base(other,{...s,seed:s.seed+731},phase,s.layer);c.globalCompositeOperation=s.blend;c.drawImage(other,0,0);c.globalCompositeOperation='source-over';}if(s.softness>0){const copy=document.createElement('canvas');copy.width=copy.height=w;copy.getContext('2d').drawImage(canvas,0,0);const pad=Math.ceil(s.softness*w/1024*4),extended=document.createElement('canvas');extended.width=extended.height=w+2*pad;const ec=extended.getContext('2d');for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++)ec.drawImage(copy,pad+x*w,pad+y*w);c.clearRect(0,0,w,w);c.filter=`blur(${s.softness*w/1024}px)`;c.drawImage(extended,-pad,-pad);c.filter='none';}if(s.invert||s.binary||s.contrast!==1||s.transparent){let im=c.getImageData(0,0,w,w),d=im.data;for(let i=0;i<d.length;i+=4){let v=Math.max(0,Math.min(255,(d[i]-127.5)*s.contrast+127.5));if(s.binary)v=v>=s.threshold?255:0;if(s.invert)v=255-v;if(s.transparent){d[i]=d[i+1]=d[i+2]=0;d[i+3]=255-v;}else d[i]=d[i+1]=d[i+2]=v;}c.putImageData(im,0,0);}return canvas;}
